server:
  port: 8878

spring:
  application:
    name: myshortlink

  mvc:
    pathmatch:
      use-suffix-pattern: true
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML
    prefix: classpath:/page/html
    servlet:
      content-type: text/html
    suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://94.191.93.211:3306/testdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  redis:
    database: 0
    host: 94.191.93.211
    password: 'WangYueYu4NiBa'
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mybatis-mapper/**/*.xml
